name: flutter_app
description: "A clean architecture Flutter project with Hooks_Riverpod"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  dio: ^5.8.0+1

  geocoding: ^3.0.0
  geolocator: ^13.0.4

  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  shimmer: ^3.0.0
  intl: ^0.20.2
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  go_router: ^14.8.1

cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4

flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
